# Generated by Django 3.1.4 on 2021-01-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210106_0615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
